// frontend/src/app/components/section/section.component.ts
import { CommonModule } from '@angular/common'
import { Component, EventEmitter, Input, Output } from '@angular/core'
import type { PublicItem, PublicSection } from '@lafontaine/backend/src/types'

@Component({
  selector: 'app-section',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './section.component.html',
  styleUrl: './section.component.scss',
})
export class SectionComponent {
  @Input() section!: PublicSection
  @Input() set items(value: PublicItem[]) {
    this._items =
      this.section?.name === 'Bières' ? this.reorderBeers(value) : value
  }
  get items(): PublicItem[] {
    return this._items
  }
  private _items: PublicItem[] = []

  @Input() isExpanded = false
  @Input() isLoading = false

  @Output() sectionClick = new EventEmitter<number>()

  onSectionClick(): void {
    this.sectionClick.emit(this.section.sectionId)
  }

  private reorderBeers(beers: PublicItem[]): PublicItem[] {
    const saintLazare = beers.filter((b) => b.name.includes('Saint-Lazare'))
    const supplement = beers.filter((b) => b.name === 'Supplément de sirop')
    const others = beers.filter(
      (b) =>
        !b.name.includes('Saint-Lazare') && b.name !== 'Supplément de sirop'
    )

    return [...saintLazare, ...others, ...supplement]
  }
}

<div class="section-container">
  <div class="section-header" (click)="onSectionClick()" [class.expanded]="isExpanded">
    <h2 class="section-title">{{ section.name }}</h2>
    <div class="section-toggle">
      <span class="toggle-icon">{{ isExpanded ? '−' : '+' }}</span>
    </div>
  </div>

  <div class="section-content" [class.expanded]="isExpanded">
    <div class="section-content-inner">
      @if (isLoading) {
        <div class="loading">
          <p>Chargement des items...</p>
        </div>
      }
      @if (!isLoading && items.length > 0) {
        <div class="items-list">
          @for (item of items; track item; let i = $index) {
            <div class="item-card" [style.animation-delay]="i * 40 + 'ms'">
              <div class="item-info">
                <h3 class="item-name">{{ item.name }}</h3>
                <div class="item-details">
                  @if (item.origin) {
                    <span class="item-origin">{{ item.origin }}</span>
                  }
                  @if (item.capacity && item.unit) {
                    <span class="item-capacity">{{ item.capacity | number:'1.0-1':'fr' }} {{ item.unit }}</span>
                  }
                  @if (!item.isAvailable) {
                    <span class="item-unavailable">Non disponible</span>
                  }
                </div>
              </div>
              <span class="item-price">{{ item.price | number:'1.2-2':'en' }} €</span>
            </div>
          }
        </div>
      }
      @if (!isLoading && items.length === 0) {
        <div class="no-items">
          <p>Aucun item disponible dans cette section.</p>
        </div>
      }
    </div>
  </div>
</div>

// frontend/src/components/Section.tsx
import type { PublicItem, PublicSection } from "@lafontaine/backend";

type Props = {
	section: PublicSection;
	items: PublicItem[];
	isExpanded: boolean;
	onToggle: (sectionId: number) => void;
};

function reorderBeers(beers: PublicItem[]): PublicItem[] {
	const saintLazare = beers.filter((b) => b.name.includes("Saint-Lazare"));
	const supplement = beers.filter((b) => b.name === "Supplément de sirop");
	const others = beers.filter(
		(b) => !b.name.includes("Saint-Lazare") && b.name !== "Supplément de sirop",
	);
	return [...saintLazare, ...others, ...supplement];
}

export function Section({ section, items, isExpanded, onToggle }: Props) {
	const displayItems = section.name === "Bières" ? reorderBeers(items) : items;

	return (
		<div>
			<button type="button" onClick={() => onToggle(section.sectionId)}>
				<h2>{section.name}</h2>
				<span>{isExpanded ? "−" : "+"}</span>
			</button>

			{isExpanded && (
				<div>
					{displayItems.map((item) => (
						<div key={`${item.name}-${item.capacity}-${item.unit}`}>
							<div>
								<h3>{item.name}</h3>
								<div>
									{item.origin && <span>{item.origin}</span>}
									{item.capacity !== null && item.unit && (
										<span>
											{new Intl.NumberFormat("fr").format(item.capacity)} {item.unit}
										</span>
									)}
									{!item.isAvailable && <span>Non disponible</span>}
								</div>
							</div>
							<span>{item.price.toFixed(2)} €</span>
						</div>
					))}

					{displayItems.length === 0 && <p>Aucun item disponible dans cette section.</p>}
				</div>
			)}
		</div>
	);
}
