// frontend/src/components/Menu.tsx
import type { PublicItem, PublicSection } from "@lafontaine/backend";
import { useEffect, useState } from "react";
import logo from "@/assets/logo.svg";
import { SOCIAL_LINKS } from "@/lib/constants";
import { getItemsBySection, getSections } from "@/services/menu";
import { Section } from "./Section";

export function Menu() {
	const [sections, setSections] = useState<PublicSection[]>([]);
	const [items, setItems] = useState<Record<number, PublicItem[]>>({});
	const [loading, setLoading] = useState(true);
	const [expanded, setExpanded] = useState<Set<number>>(new Set());
	const [search, setSearch] = useState("");

	useEffect(() => {
		getSections()
			.then(async (data) => {
				setSections(data);
				const results = await Promise.all(
					data.map((s) =>
						getItemsBySection(s.sectionId).then((items) => [s.sectionId, items] as const),
					),
				);
				setItems(Object.fromEntries(results));
			})
			.catch(console.error)
			.finally(() => setLoading(false));
	}, []);

	const toggleSection = (sectionId: number) => {
		setExpanded((prev) => {
			const next = new Set(prev);
			if (next.has(sectionId)) {
				next.delete(sectionId);
			} else {
				next.add(sectionId);
			}
			return next;
		});
	};

	const term = search.toLowerCase().trim();

	const filteredSections = term
		? sections.filter((section) =>
				(items[section.sectionId] ?? []).some(
					(item) =>
						item.name.toLowerCase().includes(term) || item.origin?.toLowerCase().includes(term),
				),
			)
		: sections;

	const isExpanded = (sectionId: number) =>
		term ? filteredSections.some((s) => s.sectionId === sectionId) : expanded.has(sectionId);

	return (
		<div>
			<div>
				<img src={logo} alt="Logo La Fontaine Mons" />
				<h1>Carte - Boissons & Desserts</h1>
				<div>
					<p>N'hésite pas à laisser un avis sur Google</p>
					<a href={SOCIAL_LINKS.tripadvisor} target="_blank" rel="noopener noreferrer">
						TripAdvisor
					</a>
					<a href={SOCIAL_LINKS.facebook} target="_blank" rel="noopener noreferrer">
						Facebook
					</a>
				</div>
			</div>

			<div>
				{loading ? (
					<p>Chargement du menu...</p>
				) : (
					<>
						<input
							type="text"
							placeholder="Rechercher une boisson..."
							value={search}
							onChange={(e) => setSearch(e.target.value)}
						/>

						{filteredSections.map((section) => (
							<Section
								key={section.sectionId}
								section={section}
								items={items[section.sectionId] ?? []}
								isExpanded={isExpanded(section.sectionId)}
								onToggle={toggleSection}
							/>
						))}

						{term && filteredSections.length === 0 && <p>Aucun résultat pour "{search}"</p>}

						{sections.length === 0 && <p>Aucune section disponible pour le moment.</p>}
					</>
				)}
			</div>
		</div>
	);
}

// frontend/src/app/components/menu/menu.component.ts
import { Component, Input, type OnInit } from '@angular/core'
import type { PublicItem, PublicSection } from '@lafontaine/backend/src/types'
import { MenuService } from '../../services/menu.service'
import { SectionComponent } from '../section/section.component'

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [SectionComponent],
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.scss',
})
export class MenuComponent implements OnInit {
  @Input() facebookUrl = ''
  @Input() tripadvisorUrl = ''
  @Input() googleUrl = ''

  sections: PublicSection[] = []
  sectionsLoading = true
  sectionsError: string | null = null
  sectionItems: { [sectionId: number]: PublicItem[] } = {}
  expandedSections: Set<number> = new Set()
  loadingSections: Set<number> = new Set()

  constructor(private menuService: MenuService) {}

  ngOnInit(): void {
    this.loadSections()
  }

  loadSections(): void {
    this.menuService.getAllSections().subscribe({
      next: (sections) => {
        this.sections = sections
        this.sectionsLoading = false
      },
      error: (error) => {
        this.sectionsLoading = false
        console.error('Error loading sections:', error)
      },
    })
  }

  onSectionClick(sectionId: number): void {
    if (this.expandedSections.has(sectionId)) {
      this.expandedSections.delete(sectionId)
    } else {
      this.expandedSections.add(sectionId)
      if (!this.sectionItems[sectionId]) {
        this.loadSectionItems(sectionId)
      }
    }
  }

  loadSectionItems(sectionId: number): void {
    this.loadingSections.add(sectionId)

    this.menuService.getItemsBySection(sectionId).subscribe({
      next: (items) => {
        this.sectionItems[sectionId] = items
        this.loadingSections.delete(sectionId)
      },
      error: (error) => {
        this.loadingSections.delete(sectionId)
        console.error(`Error loading items in section ${sectionId}:`, error)
      },
    })
  }

  isSectionExpanded(sectionId: number): boolean {
    return this.expandedSections.has(sectionId)
  }

  isSectionLoading(sectionId: number): boolean {
    return this.loadingSections.has(sectionId)
  }

  getSectionItems(sectionId: number): PublicItem[] {
    return this.sectionItems[sectionId] || []
  }
}

<div class="hero-banner">
  <div class="hero-overlay"></div>
  <div class="hero-content">
    <div class="brewery-logo">
      <img src="assets/logo.svg" alt="Logo La Fontaine Mons" class="logo-image">
    </div>
    <h1 class="menu-title">Carte - Boissons & Desserts</h1>
    <div class="social-media-container">
      <a [href]="googleUrl" target="_blank" aria-label="Google Avis" class="google-link">
        <i class="fab fa-google"></i>
      </a>
      <a [href]="tripadvisorUrl" target="_blank" aria-label="TripAdvisor" class="tripadvisor-link">
        <i class="fab fa-tripadvisor"></i>
      </a>
      <a [href]="facebookUrl" target="_blank" aria-label="Facebook" class="facebook-link">
        <i class="fab fa-facebook-f"></i>
      </a>
    </div>
  </div>
</div>

<div class="menu-container">
  @if (sectionsLoading()) {
    <div class="loading">
      <p>Chargement du menu...</p>
    </div>
  }

  @if (!sectionsLoading()) {
    <div class="search-bar">
      <i class="fas fa-search search-icon"></i>
      <input
        type="text"
        class="search-input"
        placeholder="Rechercher une boisson..."
        [value]="searchTerm()"
        (input)="onSearchInput($event)">
    </div>

    <div class="sections-list">
      @for (section of filteredSections(); track section) {
        <app-section
          [section]="section"
          [items]="getSectionItems(section.sectionId)"
          [isExpanded]="isSectionExpanded(section.sectionId)"
          [isLoading]="isSectionLoading(section.sectionId)"
          (sectionClick)="onSectionClick($event)">
        </app-section>
      }
    </div>

    @if (searchTerm().trim() && filteredSections().length === 0) {
      <div class="no-results">
        <p>Aucun résultat pour "{{ searchTerm() }}"</p>
      </div>
    }
  }

  @if (!sectionsLoading() && sections().length === 0) {
    <div class="no-sections">
      <p>Aucune section disponible pour le moment.</p>
    </div>
  }
</div>
