// frontend/src/components/Footer.tsx
export function Footer() {
	const year = new Date().getFullYear();

	return (
		<footer>
			<div>
				<span>Powered by </span>
				<a
					href="https://www.linkedin.com/in/emmanu%C3%ABl-caputo-a46173235/"
					target="_blank"
					rel="noopener noreferrer"
				>
					Manu Caputo
				</a>
			</div>
			<div>© {year} La Fontaine Mons</div>
		</footer>
	);
}

// frontend/src/app/components/footer/footer.component.ts
import { Component } from "@angular/core";

@Component({
	selector: "app-footer",
	standalone: true,
	imports: [],
	templateUrl: "./footer.component.html",
	styleUrl: "./footer.component.scss",
})
export class FooterComponent {
	currentYear = new Date().getFullYear();
}

<footer class="app-footer">
  <div class="footer-content">
    <div class="powered-by">
      <span class="powered-text">Powered by</span>
      <a
        href="https://www.linkedin.com/in/emmanu%C3%ABl-caputo-a46173235/"
        target="_blank"
        rel="noopener noreferrer"
        class="developer-link"
      >
        <span class="developer-name">Manu Caputo</span>
      </a>
    </div>
    <div class="copyright">
      <span>© {{ currentYear }} La Fontaine Mons</span>
    </div>
  </div>
  <span class="version">v{{ version }}</span>
</footer>
